# Generated by Django 5.2.17 on 2026-09-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(verbose_name='Fecha de atención')),
                ('diagnostico', models.CharField(max_length=300, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('veterinario_responsable', models.CharField(max_length=150, verbose_name='Veterinario responsable')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('animal', models.ForeignKey(help_text='El animal puede recibir varias atenciones (historial clínico).', on_delete=django.db.models.deletion.PROTECT, related_name='atenciones_medicas', to='animales.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Atención veterinaria',
                'verbose_name_plural': 'Atenciones veterinarias',
                'ordering': ['-fecha_atencion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='atencion_costo_gte_0')],
            },
        ),
    ]
