# Generated by Django 5.2.17 on 2026-09-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atencionveterinaria',
            table='atenciones_veterinarias',
        ),
    ]
