# Generated by Django 5.2.17 on 2026-09-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albergues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('edad_aproximada', models.PositiveIntegerField(help_text='Debe ser mayor o igual a 0.', verbose_name='Edad aproximada (años)')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=20, verbose_name='Sexo')),
                ('estado_actual', models.CharField(choices=[('En Albergue', 'En Albergue'), ('En Adopción', 'En Adopción'), ('Adoptado', 'Adoptado'), ('En Tratamiento', 'En Tratamiento'), ('Fallecido', 'Fallecido')], default='En Albergue', max_length=30, verbose_name='Estado actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('edad_aproximada__gte', 0)), name='animal_edad_aproximada_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('motivo_ingreso', models.CharField(max_length=250, verbose_name='Motivo de ingreso')),
                ('albergue_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='albergues.albergue', verbose_name='Albergue inicial')),
                ('animal', models.ForeignKey(help_text='PROTECT: no permite borrar el animal si ya existe su historial.', on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='animales.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(blank=True, help_text='Vacío = el animal permanece en este albergue.', null=True, verbose_name='Fecha de salida')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('albergue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='albergues.albergue', verbose_name='Albergue')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='animales.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Ubicación temporal',
                'verbose_name_plural': 'Ubicaciones temporales',
                'ordering': ['-fecha_entrada'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_salida__gte', models.F('fecha_entrada')), ('fecha_salida__isnull', True), _connector='OR'), name='ubicacion_fecha_salida_no_anterior_a_entrada')],
            },
        ),
    ]
