# Generated by Django 5.2.17 on 2026-09-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField(verbose_name='Fecha de adopción')),
                ('seguimiento_post_adopcion', models.TextField(blank=True, verbose_name='Seguimiento post adopción')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
                'ordering': ['-fecha_adopcion'],
            },
        ),
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Adoptante',
                'verbose_name_plural': 'Adoptantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='adopciones.adopcion', verbose_name='Adopción')),
            ],
            options={
                'verbose_name': 'Seguimiento de adopción',
                'verbose_name_plural': 'Seguimientos de adopción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='adopciones.adoptante', verbose_name='Adoptante')),
                ('animal', models.ForeignKey(help_text='Un animal puede tener MÚLTIPLES solicitudes antes de ser adoptado.', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='animales.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Solicitud de adopción',
                'verbose_name_plural': 'Solicitudes de adopción',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='adopcion',
            name='solicitud',
            field=models.OneToOneField(help_text='Solo una adopción por solicitud Aprobada.', on_delete=django.db.models.deletion.PROTECT, related_name='adopcion', to='adopciones.solicitudadopcion', verbose_name='Solicitud'),
        ),
    ]
