# Generated by Django 5.2.17 on 2026-09-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adopcion',
            table='adopciones',
        ),
        migrations.AlterModelTable(
            name='adoptante',
            table='adoptantes',
        ),
        migrations.AlterModelTable(
            name='seguimientoadopcion',
            table='seguimientos_adopcion',
        ),
        migrations.AlterModelTable(
            name='solicitudadopcion',
            table='solicitudes_adopcion',
        ),
    ]
